### ISSUE TITLE
[discussion] Future plans

### ISSUE THREAD

**Issue by jotaf98** [shd101wyy/logic.js#2]
Hey, just wanted to say that this is pretty awesome! Any future plans, or is the library considered more-or-less finished?

My impression is that JS is not a moving target (new ES versions come out but browsers and engines have pretty good backward-compatibility), so barring any new bugs maybe it's not needed.

But I wanted to say thanks and know a bit more. I tried a [much older and unmaintained repo](https://github.com/mcsoto/LogicJS) that nonetheless has a lot of users, and I ran into a lot of problems; this one was a breeze to use so f ar!

**Comment by shd101wyy** [comment]
Hi @jotaf98 , thank you for your compliments. I would say that this library is already finished. I started this project as a course project when I was still in college few years ago. Now I don't really remember many details about the implementation. It shouldn't be hard to rewrite the library in other programming languages. You could take a look at [this markdown file](https://github.com/shd101wyy/logic.js/blob/master/docs/logic.js.md) as a reference. I did use a few special features like Generators, Set from ES6 standard, so it might be hard to rewrite the library in programming languages that don't support them.

**Comment by jotaf98** [comment]
Thanks! Actually I'm not looking to rewrite it in another language, ES6 is perfectly good.

The docs are super good, so I think that maintenance won't be a problem. The main obstacle (in the event that I find a bug) would be my limited experience with miniKanren.
